services:
    paper:
      image: jaminima/paper
      stdin_open: true
      tty: true
      ports:
        - "25565:25565"
        - "19132:19132/udp"
        - "8804:8804"
        - "8100:8100"
      volumes:
        - ./server:/minecraft
